export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  dateModified?: string;
  author: string;
  category: string;
  image: string;
  coverImage?: string;
  slug: string;
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  ogImage?: string;
  faqs?: FaqItem[];
  source?: 'local' | 'wordpress';
}

export const blogPosts: BlogPost[] = [
  {
    id: '1778247712910',
    title: "DCD Approval Dubai for Fitout Projects: Complete 2026 Guide",
    slug: 'civil-defense-approval-dubai-fitout-projects',
    category: "Dubai Civil Defence",
    author: "Building Approvals Dubai",
    date: '2026-05-08',
    dateModified: '2026-06-05',
    excerpt: "Learn Civil Defense Approval Dubai requirements for fit-out projects in 2026, including process, documents, inspections, timelines, common delays, and expert tips.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-civil-defence-list-1778247712910.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-civil-defence-cover-1778247712910.jpg",
    metaTitle: "Civil Defense Approval Dubai for Fitout Projects 2026",
    metaDescription: "Learn Civil Defense approval Dubai requirements for fit-out projects in 2026, including process, documents, inspections, common delays, and expert tips.",
    keywords: ["DCD Approval", "dubai civil defence approval"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-civil-defence-cover-1778247712910.jpg",
  },

  {
    id: '1778239781036',
    title: "Dubai Municipality Approval Documents Checklist 2026",
    slug: 'dubai-municipality-approval-documents-2026',
    category: "Dubai Municipality",
    author: "Building Approvals Dubai",
    date: '2026-05-08',
    excerpt: "Get a clear Dubai Municipality approval document checklist for 2026, including drawings, NOCs, IDs, Ejari, trade license, and practical tips to avoid delays.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-list-1778239781036.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-cover-1778239781036.jpg",
    metaTitle: "Dubai Municipality Approval Documents Checklist 2026",
    metaDescription: "Get a clear Dubai Municipality approval document checklist for 2026, including drawings, NOCs, IDs, Ejari, trade license, and practical tips to avoid delays.",
    keywords: ["Dubai Municipality", "dm approval"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-cover-1778239781036.jpg",
    faqs: [
      { question: 'What documents are required for Dubai Municipality approval?', answer: 'The main documents include Emirates ID or passport, trade license, title deed, Ejari, landlord NOC, existing layout, proposed drawings, and project-specific technical drawings including structural or MEP plans.' },
      { question: 'Is Ejari required for DM approval?', answer: 'Yes, Ejari is commonly required for tenant-related commercial fit-out, office renovation, shop modification, and leased property approval applications.' },
      { question: 'Do I need Dubai Civil Defence approval with DM approval?', answer: 'Yes, if your project affects fire alarm, fire fighting, emergency exits, kitchen exhaust, sprinklers, or life safety systems, DCD approval may be required alongside DM approval.' },
      { question: 'Can I submit the Dubai Municipality approval myself?', answer: 'Some basic applications may be handled directly, but technical projects usually require a registered consultant or approved contractor.' },
      { question: 'Why does DM approval get rejected?', answer: 'Common reasons include missing NOCs, unclear drawings, a mismatch between documents, unapproved contractors, structural changes without calculations, and incomplete MEP details.' },
      { question: 'How can I avoid delays in municipality approval in Dubai?', answer: 'Prepare all documents before submission, use updated drawings, confirm authority requirements, appoint qualified professionals, and check that every document matches the project scope.' },
    ],
  },

  {
    id: '1778068785631',
    title: "Dubai Municipality Services: Complete Guide for Residents",
    slug: 'dubai-municipality-approvals-guide-2026',
    category: "General",
    author: "Building Approvals Dubai",
    date: '2026-05-06',
    dateModified: '2026-06-05',
    excerpt: "Learn about Dubai Municipality services, DM approval process, rules, fees, BPS Dubai, branches, and fitout approval steps for property projects.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-services-list-1778068785631.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-services-cover-1778068785631.jpg",
    metaTitle: "Dubai Municipality Approvals Services: Complete Guide 2026",
    metaDescription: "Learn about the Dubai Municipality Approvals service, DM approval process, rules, fees, BPS Dubai, branches, and fitout approval steps for property projects.",
    keywords: ["dm dubai", "bps dubai", "dm municipality"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-dubai-municipality-services-cover-1778068785631.jpg",
  },

  {
    id: '1777732827331',
    title: "DM Municipality Salon Approval in Dubai: Complete 2026 Guide",
    slug: 'dm-municipality-approvals-salon-approval',
    category: "Interior Fitout",
    author: "Building Approvals Dubai",
    date: '2026-05-02',
    dateModified: '2026-06-05',
    excerpt: "Learn how to get salon approval in Dubai through DM Municipality, BPS, fitout approval, documents, inspections, and practical compliance tips for 2026.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-interior-fitout-list-1777732827331.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-interior-fitout-cover-1777732827331.jpg",
    metaTitle: "DM Municipality Salon Approval in Dubai 2026 Guide",
    metaDescription: "Learn how to get salon approval in Dubai through DM Municipality, BPS, fitout approval, documents, inspections, and practical compliance tips for 2026.",
    keywords: ["salon approval", "dm dubai", "dm approval", "fitout approval", "dm dubai", "dm bps"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-interior-fitout-cover-1777732827331.jpg",
  },

  {
    id: '1776666807951',
    title: "Villa Modification Approval in Dubai: Complete 2026 Guide",
    slug: 'modification-approval-villa-dubai',
    category: "Modification Approval",
    author: "Building Approvals Dubai",
    date: '2026-04-20',
    dateModified: '2026-06-05',
    excerpt: "Learn the villa modification approval process in Dubai for 2026. Understand Dubai Municipality permits, key documents, steps, timelines, and delays.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-modification-approval-list-1776666807951.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-modification-approval-cover-1776666807951.jpg",
    metaTitle: "Villa Modification Approval in Dubai | 2026 Guide",
    metaDescription: "Learn the villa modification approval process in Dubai for 2026. Understand Dubai Municipality permits, key documents, steps, timelines, and delays.",
    keywords: [],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/building-approvals-dubai-modification-approval-cover-1776666807951.jpg",
  },

  {
    id: '1776065501699',
    title: 'Top 10 Interior Fitout Companies Dubai 2026',
    slug: 'top-10-interior-fitout-companies-dubai-2026',
    category: 'Interior Fitout',
    author: 'Building Approvals Dubai',
    date: '2026-04-13',
    excerpt: 'Discover the top 10 interior fitout companies in Dubai for offices, villas, restaurants, and renovations, with practical tips to choose the right partner.',
    image: 'https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-interior-fitout-list-1776065501699.jpg',
    coverImage: 'https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-interior-fitout-cover-1776065501699.jpg',
    metaTitle: 'Top 10 Interior Fitout Companies Dubai 2026',
    metaDescription: 'Discover the top 10 interior fitout companies in Dubai for offices, villas, restaurants, and renovations, with practical tips to choose the right partner.',
    keywords: ['Interior', 'Fitout', 'Companies', 'Dubai', '2026'],
    ogImage: 'https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-interior-fitout-cover-1776065501699.jpg',
  },

  {
    id: '1770279885245',
    title: "Municipality Approval in Dubai: Fit-Out Approval Violations",
    slug: 'dubai-municipality-approvals-common-violations',
    category: "Dubai Municipality Approvals",
    author: "Building Approvals Dubai",
    date: '2026-02-05',
    dateModified: '2026-06-05',
    excerpt: "Avoid the Dubai Municipality Approvals delay in Dubai. Most common fit-out approval violations, why they happen, and how to fix drawings. Free Consultation",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-list-1770279885245.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-cover-1770279885245.jpg",
    metaTitle: "Dubai Municipality Approvals Common Violations",
    metaDescription: "Avoid the Dubai Municipality Approvals delay in Dubai. Most common fit-out approval violations, why they happen, and how to fix drawings. Free Consultation",
    keywords: ["Dm dubai", "dm approval", "municipality approval", "approvals dubai"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-cover-1770279885245.jpg",
  },

  {
    id: '1770014417337',
    title: "DSO Approval / DIEZ Approval in Dubai 2026: Complete Guide",
    slug: 'dso-approvals-dubai-complete-guide',
    category: "DSO / DIEZ Approval",
    author: "Building Approvals Dubai",
    date: '2026-02-02',
    dateModified: '2026-06-05',
    excerpt: "Learn how DSO approvals work in Dubai, the DIEZ process for fit-out projects, and why hiring a consultant avoids delays and rejections. Building Approvals",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dso-diez-approval-list-1770014417337.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dso-diez-approval-cover-1770014417337.jpg",
    metaTitle: "DSO Approvals Dubai Process 2026: A Complete Guide",
    metaDescription: "Learn how DSO approvals work in Dubai, the DIEZ process for fit-out projects, and why hiring a consultant avoids delays and rejections.",
    keywords: ["Approval Dubai", "DIEZ Approval", "DM dubai", "approvals guide"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dso-diez-approval-cover-1770014417337.jpg",
  },

  {
    id: '1769065428206',
    title: "Why hire a Consultant for Dubai Civil Defence DCD Approval?",
    slug: 'civil-defense-approvals-dubai-consultants',
    category: "Dubai Civil Defence",
    author: "Building Approvals Dubai",
    date: '2026-01-22',
    dateModified: '2026-06-05',
    excerpt: "Getting Civil Defense Approvals in Dubai is one of the most critical & often most confusing aspects of any fitout, renovation, and modification project.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-civil-defence-list-1769065428206.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-civil-defence-cover-1769065428206.jpg",
    metaTitle: "Why hire a Consultant for Civil Defense Approvals in Dubai?",
    metaDescription: "Getting Civil Defense Approvals in Dubai is one of the most critical & often most confusing aspects of any fitout, renovation, and modification project.",
    keywords: ["dda approval", "fire and safety approval dubai", "dubai civil defence approval"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-civil-defence-cover-1769065428206.jpg",
  },

  {
    id: '1768987140126',
    title: "How to get DDA Approval in Dubai 2026?",
    slug: 'dda-approvals-dubai-complete-process',
    category: "DDA Approval",
    author: "Building Approvals Dubai",
    date: '2026-01-21',
    dateModified: '2026-06-05',
    excerpt: "This explains what DDA Approvals are, who needs them, the documents required, approval types, and covered areas, so you can move forward confidently.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dda-approval-list-1768987140126.jpeg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dda-approval-cover-1768987140126.jpeg",
    metaTitle: "How to get DDA Approvals in Dubai 2026?",
    metaDescription: "This explains what DDA Approvals are, who needs them, the documents required, approval types, and covered areas, so you can move forward confidently.",
    keywords: ["Dubai", "Development", "Authority", "(DDA)", "Approval", "Dubai", "2026"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dda-approval-cover-1768987140126.jpeg",
  },

  {
    id: '1768976989112',
    title: "Dubai Municipality (DM): Approvals & Compliance Guide 2026",
    slug: 'dubai-municipality-approvals-compliance-guide',
    category: "Dubai Municipality",
    author: "Building Approvals Dubai",
    date: '2026-01-21',
    dateModified: '2026-06-05',
    excerpt: "Dubai Municipality approvals compliance guide for owners, developers & businesses: understand approvals, process steps, and avoid costly Dubai delays. Contact",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-services-ca-list-1768976989112.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-services-ca-cover-1768976989112.jpg",
    metaTitle: "Dubai Municipality Approvals Compliance Guide in Dubai",
    metaDescription: "Dubai Municipality approvals compliance guide for owners, developers & businesses: understand approvals, process steps, and avoid costly Dubai delays. Contact",
    keywords: ["Dubai", "Municipality", "(DM)", "Services", "Categories:", "Complete", "Guide", "Approvals", "Compliance", "Dubai", "(2026)"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-services-ca-cover-1768976989112.jpg",
  },

  {
    id: '1768552874848',
    title: "10 Common Fit-Out Approval Mistakes in Dubai 2026",
    slug: 'fitout-approvals-dubai-common-mistakes',
    category: "Fit-Out Approvals",
    author: "Building Approvals Dubai",
    date: '2026-01-16',
    dateModified: '2026-06-05',
    excerpt: "Fitout approvals Dubai common mistakes guide: learn what delays projects, avoid approval issues, and keep your Dubai fitout work on track. Free Consultation",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-fit-out-approval-list-1768552866539.png",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-fit-out-approval-cover-1768552866539.png",
    metaTitle: "Fitout Approvals Dubai Common Mistakes to Avoid",
    metaDescription: "Fitout approvals Dubai common mistakes guide: learn what delays projects, avoid approval issues, and keep your Dubai fitout work on track. Free Consultation",
    keywords: ["fitout approvals dubai", "dm dubai", "municipality approval"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-fit-out-approval-cover-1768552866539.png",
  },

  {
    id: '1768411786959',
    title: "DM Dubai Municipality Approval 2026 – Complete Guide",
    slug: 'dubai-municipality-approvals-permits-guide',
    category: "Dubai Municipality Approvals",
    author: "Building Approvals",
    date: '2026-01-14',
    dateModified: '2026-06-05',
    excerpt: "Dubai municipality approvals confirm that fitout approvals must meet building codes, safety rules, environmental standards, and zoning requirements in Dubai.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-list-1769065838329.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-cover-1769065838329.jpg",
    metaTitle: "Dubai Municipality Approvals Permits Guide: Fitout Projects",
    metaDescription: "Dubai municipality approvals confirm that fitout approvals must meet building codes, safety rules, environmental standards, and zoning requirements in Dubai.",
    keywords: ["Dubai", "Municipality", "Approval", "(DM)", "2026", "Complete", "Guide", "Construction", "Fit-Out", "Engineering", "Projects", "Dubai"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-dubai-municipality-cover-1769065838329.jpg",
  },

  {
    id: '1768410382547',
    title: "How to Secure a Nakheel NOC in Dubai 2026",
    slug: 'how-to-secure-a-nakheel-noc-in-dubai-2026',
    category: "Nakheel NOC",
    author: "Building Approvals Dubai",
    date: '2026-01-14',
    dateModified: '2026-05-08',
    excerpt: "This guide breaks down everything you need — from why the NOC matters, when it's required, how to apply, and smart tips to avoid delays.",
    image: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-nakheel-list-1769065723111.jpg",
    coverImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-nakheel-cover-1769065723111.jpg",
    metaTitle: "How to Secure a Nakheel NOC in Dubai 2026?",
    metaDescription: "This guide breaks down everything you need, from why the NOC matters, when it's required, how to apply, and smart tips to avoid delays.",
    keywords: ["Nakheel NOC", "Nakheel Dubai"],
    ogImage: "https://tey8h8kr4bvj5bie.public.blob.vercel-storage.com/blog/building-approvals-dubai-nakheel-cover-1769065723111.jpg",
    faqs: [
      { question: 'How long does Nakheel NOC take?', answer: 'Usually within 3–10 working days unless additional information or inspection is required.' },
      { question: 'Can someone apply on my behalf?', answer: 'Yes — with a valid authorization letter or Power of Attorney.' },
      { question: 'Is the NOC fee refundable?', answer: 'No, fees are generally non-refundable, even if you need to reapply.' },
      { question: 'How long is the NOC valid?', answer: 'NOCs typically have a limited validity period (usually around 30 days). Check the certificate for exact dates.' },
    ],
  },

  {
    id: '1768287588802',
    title: "How to get DEWA Approvals in Dubai 2026?",
    slug: 'how-to-get-dewa-approvals-in-dubai-2026',
    category: "DEWA Approvals",
    author: "Building Approvals Dubai",
    date: '2026-01-13',
    dateModified: '2026-05-07',
    excerpt: "This guide explains how DEWA fits into Dubai's building approvals system, the step-by-step DEWA approval process, and a complete list of documents required to avoid delays.",
    image: "/images/blog/building-approvals-dubai-dewa-approval-list.jpg",
    coverImage: "/images/blog/building-approvals-dubai-dewa-approval-cover.jpg",
    metaTitle: "How to get DEWA Approvals in Dubai 2026?",
    metaDescription: "This guide explains how DEWA fits into Dubai's building approvals system, the step-by-step DEWA approval process, and a complete list of documents required to avoid delays.",
    keywords: ["DEWA", "dewa approvals", "dewa approved contractors", "dewa approval consultant"],
    ogImage: "/images/blog/building-approvals-dubai-dewa-approval-cover.jpg",
  },

  {
    id: '4',
    title: "How to get Fitout Approvals in Dubai: Step by Step Process",
    slug: 'how-to-get-fitout-approvals-in-dubai',
    category: "Fit-Out Approvals",
    author: "Building Approvals Dubai",
    date: '2026-01-09',
    dateModified: '2026-05-08',
    excerpt: "Setting up a new office, restaurant, shop, or clinic in Dubai is exciting, but before you start the interior work, you need the right fit-out approvals.",
    image: "/images/blog/building-approvals-dubai-fit-out-approval-card.jpg",
    coverImage: "/images/blog/building-approvals-dubai-fit-out-cover.jpg",
    metaTitle: "How to get Fitout Approval in Dubai 2026: Complete Guide",
    metaDescription: "Complete guide to fit-out approval in Dubai for 2026. Learn the step-by-step process, required documents, authorities involved, and tips to get approvals faster for offices, restaurants, and retail spaces.",
    keywords: ["fit-out approval Dubai", "Dubai fit-out permit", "interior approval Dubai", "building approvals Dubai", "Dubai Municipality fit-out", "DCD fit-out approval", "fit-out consultant Dubai"],
    ogImage: "/images/blog/building-approvals-dubai-fit-out-cover.jpg",
  },

  {
    id: '1',
    title: "Dubai Municipality (DM) Approval Process 2026: Step by Step",
    slug: 'dubai-municipality-approval-process-2026',
    category: "Dubai Municipality",
    author: "Building Approvals Dubai",
    date: '2024-12-26',
    dateModified: '2026-05-08',
    excerpt: "Step-by-step guide to Dubai Municipality building approvals in 2026, including required documents, timelines, and expert tips for residential and commercial projects.",
    image: "/images/blog/building-approvals-dubai-municipality-card.jpg",
    coverImage: "/images/blog/building-approvals-dubai-municipality-cover.jpg",
    metaTitle: "Dubai Municipality Approval Process 2026 | Complete Building Approvals Guide",
    metaDescription: "Step-by-step guide to Dubai Municipality building approvals in 2026. Learn the complete process, required documents, timelines, and expert tips for residential and commercial projects.",
    keywords: ["Dubai Municipality approval", "building approvals Dubai", "Dubai building permit", "construction approval Dubai", "Dubai Municipality 2026", "building permit process Dubai"],
    ogImage: "/images/blog/building-approvals-dubai-municipality-cover.jpg",
  },

  {
    id: '2',
    title: "Dubai Municipality Approvals (DM): Updated Rules 2026",
    slug: 'dubai-municipality-approvals-dm-2026-updated-rules',
    category: "Dubai Municipality",
    author: "Building Approvals Dubai",
    date: '2024-12-26',
    dateModified: '2026-05-08',
    excerpt: "Discover the latest updates to Dubai Municipality approval processes in 2026, including new digital platforms, streamlined procedures, and enhanced compliance requirements.",
    image: "/images/blog/building-approvals-dubai-municipality-update-card.jpg",
    coverImage: "/images/blog/building-approvals-dubai-municipality-update-cover.webp",
    metaTitle: "Dubai Municipality Approvals (DM) 2026: Updated Rules & Digital Innovations",
    metaDescription: "Discover the latest updates to Dubai Municipality approval processes in 2026, including new digital platforms, streamlined procedures, and enhanced compliance requirements.",
    keywords: ["Dubai", "Municipality", "Approvals", "(DM)", "2026:", "Updated", "Rules", "Digital", "Innovations"],
    ogImage: "/images/blog/building-approvals-dubai-municipality-update-cover.webp",
  },

  {
    id: '3',
    title: "Dubai Civil Defence Approval (DCD) – Complete Guide for 2026",
    slug: 'dcd-approval-dubai-complete-process',
    category: "Dubai Civil Defence",
    author: "Building Approvals Dubai",
    date: '2026-01-08',
    dateModified: '2026-05-11',
    excerpt: "Get hassle-free DCD Approval in Dubai with expert support for submissions, drawings, and follow-ups through the DCD Portal. Fast, clear, and reliable.",
    image: "/images/blog/building-approvals-dubai-civil-defence-approval-card.jpg",
    coverImage: "/images/blog/building-approvals-dubai-civil-defence-approval-card.jpg",
    metaTitle: "Dubai Civil Defence Approval (DCD) – Complete Guide for 2026",
    metaDescription: "Get hassle-free DCD Approval in Dubai with expert support for submissions, drawings, and follow-ups through the DCD Portal. Fast, clear, and reliable.",
    keywords: ["Dubai", "Civil", "Defence", "Approval", "(DCD)", "Complete", "Guide", "2026"],
    ogImage: "/images/blog/building-approvals-dubai-civil-defence-approval-card.jpg",
  }
];
